
CREATE TABLE IF NOT EXISTS user (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  token_id BIGINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS user_token (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED,
    token VARCHAR(255) NOT NULL,
    expiration DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user
    ADD CONSTRAINT fk_user_token FOREIGN KEY (token_id) REFERENCES user_token(id);

ALTER TABLE user_token
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id);

CREATE TABLE IF NOT EXISTS person (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    user_id BIGINT UNSIGNED,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

