CREATE TABLE IF NOT EXISTS logs(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    action ENUM('INSERT', 'DELETE', 'SEARCH', 'UPDATE'),
    user_id BIGINT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

ALTER TABLE expense
    ADD COLUMN intermediarys JSON;

ALTER TABLE expense
    ADD COLUMN paid TINYINT DEFAULT 0;
